// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfEVPNiMSBqL5X8zEs8Zro7dnYApdodxA',
    appId: '1:309396762686:web:8192219364ff3837b6216f',
    messagingSenderId: '309396762686',
    projectId: 'flask-test-a3ccc',
    authDomain: 'flask-test-a3ccc.firebaseapp.com',
    databaseURL: 'https://flask-test-a3ccc.firebaseio.com',
    storageBucket: 'flask-test-a3ccc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAruSaw3kL0LZtkUQqRr_iPGvBQX8DA8Lg',
    appId: '1:309396762686:android:84b58afc6b86e145b6216f',
    messagingSenderId: '309396762686',
    projectId: 'flask-test-a3ccc',
    databaseURL: 'https://flask-test-a3ccc.firebaseio.com',
    storageBucket: 'flask-test-a3ccc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBltPpfXN8ssOlTcPaHi2i20YvwERy-mbA',
    appId: '1:309396762686:ios:608a6893aaf53f13b6216f',
    messagingSenderId: '309396762686',
    projectId: 'flask-test-a3ccc',
    databaseURL: 'https://flask-test-a3ccc.firebaseio.com',
    storageBucket: 'flask-test-a3ccc.appspot.com',
    iosBundleId: 'com.example.ecocare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBltPpfXN8ssOlTcPaHi2i20YvwERy-mbA',
    appId: '1:309396762686:ios:77098ca41d1de5fbb6216f',
    messagingSenderId: '309396762686',
    projectId: 'flask-test-a3ccc',
    databaseURL: 'https://flask-test-a3ccc.firebaseio.com',
    storageBucket: 'flask-test-a3ccc.appspot.com',
    iosBundleId: 'com.example.ecocare.RunnerTests',
  );
}
